### ISSUE TITLE
Fix(favicon): Barely visible in darkmode.

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-blog#3]
Should be same as in https://github.com/bitcartcc/bitcart-admin/issues/7

**Comment by orestischaral** [comment]
I do not have access rights to push a new branch on this repository
![Capture](https://user-images.githubusercontent.com/33599092/94821434-3fb5df80-040a-11eb-8844-57d0f1aa2032.PNG)

**Comment by MrNaif2018** [comment]
See https://github.com/bitcartcc/bitcart/blob/master/CONTRIBUTING.md#getting-the-sources
You should fork the repo and push to your fork, and then open PR from it

**Comment by MrNaif2018** [comment]
Closed by #4
