### ISSUE TITLE
Fix image sizing issues

### ISSUE THREAD

**Issue by MrNaif2018** [bitcartcc/bitcart-blog#6]
![изображение](https://user-images.githubusercontent.com/39452697/94968744-209e7700-050a-11eb-889d-2e480c4992b5.png)
Currently, image thumbnails are displayed cropped.
We should either de-scale images when displaying, or make them all one size.
Image URLs can be got here:
https://github.com/bitcartcc/bitcart-blog/blob/master/content/articles/bitcartcc-updates-summary-august-2020.md
https://github.com/bitcartcc/bitcart-blog/blob/master/content/articles/contribute-to-bitcartcc-this-hacktoberfest.md
In frontmatter `img` attribute

**Comment by TobyAsE** [comment]
I'd like to work on this

**Comment by MrNaif2018** [comment]
Hi! Thank you very much! Feel free to ask any questions when implementing!
